import {
  Hand,
  UserRound,
  Sparkles,
  Droplet,
  Syringe,
  Gauge,
  DoorOpen,
  Sofa,
  Camera,
  Video,
  GraduationCap,
  ClipboardCheck,
  ShieldCheck,
  Heart,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  hand: Hand,
  user: UserRound,
  sparkles: Sparkles,
  droplet: Droplet,
  syringe: Syringe,
  gauge: Gauge,
  door: DoorOpen,
  sofa: Sofa,
  camera: Camera,
  video: Video,
  graduation: GraduationCap,
  clipboard: ClipboardCheck,
  shield: ShieldCheck,
  heart: Heart,
};